name: Deploy Flask to AWS Elastic Beanstalk

on:
  push:
    branches:
      - feat/SCRUM-7

jobs:
  deploy:
    name: Deploy Flask App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: |
        pip install -r nausica-grant-application/requirements.txt

    - name: Package Application
      run: zip -r deploy.zip . -x "venv/*" ".git/*" ".github/*"

    - name: Install AWS CLI & Elastic Beanstalk CLI
      run: |
        python -m pip install --upgrade pip
        pip install awscli
        pip install awsebcli

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}

    - name: Check if EB Environment Exists
      id: check_environment
      run: |
        aws elasticbeanstalk describe-environments --environment-names "$EB_ENVIRONMENT_NAME" --query "Environments[0].EnvironmentName" --output text || echo "Environment does not exist"

    - name: Create EB Environment if it does not exist
      if: steps.check_environment.outputs.result == 'Environment does not exist'
      run: |
        eb create "$EB_ENVIRONMENT_NAME" --region "$AWS_REGION" --platform "Python 3.9" --tier "WebServer" --scale 1 --keyname "$EB_KEYPAIR_NAME"

    - name: Deploy to Elastic Beanstalk
      run: |
        eb init "$EB_APPLICATION_NAME" --region "$AWS_REGION" --platform "Python 3.9"
        eb deploy "$EB_ENVIRONMENT_NAME"
