name: Deploy Flask to AWS Elastic Beanstalk

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy Flask App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r nausica-grant-application/requirements.txt

    - name: Package Application
      run: zip -r deploy.zip . -x "venv/*" ".git/*" ".github/*"

    - name: Install AWS CLI & Elastic Beanstalk CLI
      run: |
        python -m pip install --upgrade pip
        pip install awscli
        pip install awsebcli
        pip install --upgrade awscli botocore

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        EB_APPLICATION_NAME: ${{ secrets.EB_APPLICATION_NAME }}
        EB_ENVIRONMENT_NAME: ${{ secrets.EB_ENVIRONMENT_NAME }}
      run: |
        eb init "$EB_APPLICATION_NAME" --region "$AWS_REGION" --platform "Python 3.9"
        eb deploy "$EB_ENVIRONMENT_NAME"
